// lib/services/pdf_service.dart
import 'dart:io';
import 'package:flutter/services.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';

class PdfService {
  /// Generate and open a PDF for the given order
  static Future<void> generateAndOpenOrderPdf(Map<String, dynamic> order, List<Map<String, dynamic>> dishes) async {
    final pdf = pw.Document();
    
    // Load fonts/images if needed
    // final font = await PdfGoogleFonts.nunitoExtraLight();
    
    final dateStr = order['date'] ?? '';
    final customerName = order['customerName'] ?? 'Valued Customer';
    final mobile = order['mobile'] ?? '';
    final firmId = order['firmId'] ?? '';
    
    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return [
            _buildHeader(firmId),
            pw.SizedBox(height: 20),
            _buildOrderDetails(order, dateStr, customerName, mobile),
            pw.SizedBox(height: 20),
            _buildDishTable(dishes),
            pw.SizedBox(height: 20),
            _buildTotals(order),
            pw.SizedBox(height: 40),
            _buildFooter(),
          ];
        },
      ),
    );

    // Open/Share
    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
      name: 'Order_${order['id']}_$customerName.pdf',
    );
  }

  static pw.Widget _buildHeader(String firmId) {
    return pw.Header(
      level: 0,
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text('RuchiServ Catering', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
          pw.Text('Firm ID: $firmId', style: const pw.TextStyle(fontSize: 12)),
        ],
      ),
    );
  }

  static pw.Widget _buildOrderDetails(Map<String, dynamic> order, String date, String name, String mobile) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text('Order Confirmation', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
        pw.SizedBox(height: 10),
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text('Customer: $name'),
                pw.Text('Mobile: $mobile'),
                pw.Text('Location: ${order['location'] ?? ''}'),
              ],
            ),
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.end,
              children: [
                pw.Text('Date: $date'),
                pw.Text('Time: ${order['eventTime'] ?? ''}'),
                pw.Text('Pax: ${order['totalPax'] ?? 0}'),
              ],
            ),
          ],
        ),
      ],
    );
  }

  static pw.Widget _buildDishTable(List<Map<String, dynamic>> dishes) {
    final headers = ['Dish Name', 'Category', 'Pax', 'Rate', 'Amount'];
    final data = dishes.map((d) {
      final pax = int.tryParse(d['pax']?.toString() ?? '0') ?? 0;
      final rate = double.tryParse(d['rate']?.toString() ?? '0') ?? 0;
      final amount = pax * rate;
      return [
        d['name'] ?? '',
        d['category'] ?? '',
        pax.toString(),
        rate.toStringAsFixed(2),
        amount.toStringAsFixed(2),
      ];
    }).toList();

    return pw.Table.fromTextArray(
      headers: headers,
      data: data,
      headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
      headerDecoration: const pw.BoxDecoration(color: PdfColors.grey300),
      cellAlignment: pw.Alignment.centerLeft,
      cellAlignments: {
        2: pw.Alignment.centerRight,
        3: pw.Alignment.centerRight,
        4: pw.Alignment.centerRight,
      },
    );
  }

  static pw.Widget _buildTotals(Map<String, dynamic> order) {
    final total = double.tryParse(order['finalAmount']?.toString() ?? '0') ?? 0;
    final discount = double.tryParse(order['discountPercent']?.toString() ?? '0') ?? 0;
    
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.end,
      children: [
        pw.Text('Discount: $discount%', style: const pw.TextStyle(fontSize: 12)),
        pw.Divider(),
        pw.Text('Total Amount: INR ${total.toStringAsFixed(2)}', style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
      ],
    );
  }

  static pw.Widget _buildFooter() {
    return pw.Footer(
      leading: pw.Text('Generated by RuchiServ', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey)),
      trailing: pw.Text('Thank you for your business!', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey)),
    );
  }
}
