// LOCKED: Do not edit this file without explicit user approval.
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

import '../services/biometric_service.dart';
import '../services/connectivity_service.dart';
import '../services/auth_service.dart';
import '../services/permission_service.dart';
import '../services/feature_gate_service.dart';
import '../db/database_helper.dart';
import 'package:ruchiserv/l10n/app_localizations.dart';

// @locked
import '2.0_orders_calendar_screen.dart';
import 'main_menu_screen.dart';
import '1.6_register_choice.dart';
import '1.7_forgot_password.dart';

class LoginScreen extends StatefulWidget {
  const LoginScreen({super.key});

  @override
  State<LoginScreen> createState() => _LoginScreenState();
}

class _LoginScreenState extends State<LoginScreen> {
  final _formKey = GlobalKey<FormState>();
  final _firmCtrl = TextEditingController(text: 'RCHSRV'); // default firm code if you like
  final _mobileCtrl = TextEditingController();
  final _passCtrl = TextEditingController();

  bool _isLoading = false;
  bool _biometricAvailable = false;

  @override
  @override
  void initState() {
    super.initState();
    _initAsync();
  }

  Future<void> _initAsync() async {
    await _checkBiometric();
    await _prefill();
  }

  Future<void> _prefill() async {
    final sp = await SharedPreferences.getInstance();
    final lastMobile = sp.getString('auth_mobile');
    final lastFirm = sp.getString('last_firm');
    final lastMobileBiometric = sp.getString('last_mobile');
    
    if (!mounted) return;
    
    // Prefill from last successful login (biometric or regular)
    if (lastFirm != null && lastFirm.isNotEmpty) {
      _firmCtrl.text = lastFirm;
    }
    
    // Prefer biometric mobile if available, else auth_mobile
    final mobileToUse = (lastMobileBiometric != null && lastMobileBiometric.isNotEmpty) 
        ? lastMobileBiometric 
        : lastMobile;
        
    if (mobileToUse != null && mobileToUse.isNotEmpty) {
      _mobileCtrl.text = mobileToUse;
    }
    
    // Check if biometric is enabled and auto-trigger
    final bioEnabled = sp.getBool('biometric_enabled') ?? false;
    if (bioEnabled && _biometricAvailable) {
      // Small delay to let UI settle
      await Future.delayed(const Duration(milliseconds: 500));
      if (mounted) {
        _loginWithBiometric();
      }
    }
  }

  Future<void> _checkBiometric() async {
    try {
      final ok = await BiometricService().canCheckBiometrics();
      if (!mounted) return;
      setState(() => _biometricAvailable = ok);
    } catch (_) {
      if (!mounted) return;
      setState(() => _biometricAvailable = false);
    }
  }

  Future<void> _login() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() => _isLoading = true);
    try {
      final firmId = _firmCtrl.text.trim();
      final mobile = _mobileCtrl.text.trim();
      final pass = _passCtrl.text;

      final online = await ConnectivityService().isOnline();

      bool allowed = false;
      if (online) {
        // Online path
        allowed = await AuthService.loginOnline(
          firmId: firmId,
          mobile: mobile,
          password: pass,
        );
        
        // FALLBACK: If online login fails (e.g. user only exists locally due to mock reg), try local
        if (!allowed) {
          print('LoginScreen: Online login failed, trying offline fallback...');
          allowed = await AuthService.loginOffline(
            firmId: firmId,
            mobile: mobile,
            password: pass,
          );
        }

        if (allowed) {
          await AuthService.stampLocalLogin(online: true);
        }
      } else {
        // Offline path
        // First check if allowed to login offline (time limit)
        bool canOffline = await AuthService.canLoginOffline(
          firmId: firmId,
          mobile: mobile,
        );
        
        if (canOffline) {
          // Then verify password locally
          allowed = await AuthService.loginOffline(
            firmId: firmId,
            mobile: mobile,
            password: pass,
          );
        }
        
        if (allowed) {
          await AuthService.stampLocalLogin(online: false);
        }
      }

      if (!allowed) {
        if (!mounted) return;
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(online
                ? AppLocalizations.of(context)!.invalidCredentials
                : AppLocalizations.of(context)!.offlineLoginNotAllowed),
          ),
        );
        return;
      }

      // Check subscription status
      if (await AuthService.isExpired()) {
        if (!mounted) return;
        _showExpiryDialog(lock: true);
        return;
      } else if (await AuthService.shouldWarnExpiry()) {
        if (!mounted) return;
        _showExpiryDialog(lock: false);
      }

      if (!mounted) return;
      
      // Check if this is first login (biometrics not enabled yet)
      final sp = await SharedPreferences.getInstance();
      final biometricEnabled = sp.getBool('biometric_enabled') ?? false;
      
      // Store credentials for biometric login
      await sp.setString('last_firm', firmId);
      await sp.setString('last_mobile', mobile);
      
      // Store user role for RBAC checks
      final db = await DatabaseHelper().database;
      final userList = await db.query('users', 
        where: 'mobile = ? AND firmId = ?', 
        whereArgs: [mobile, firmId],
      );
      if (userList.isNotEmpty) {
        final userRole = userList.first['role']?.toString() ?? 'Staff';
        await sp.setString('last_role', userRole);
      }
      
      // Initialize RBAC and Feature Gate services
      await PermissionService.instance.initialize();
      await FeatureGateService.instance.initialize();
      
      // Prompt for biometric enrollment if not enabled
      if (!biometricEnabled && _biometricAvailable) {
        await _promptBiometricEnrollment();
      }

      if (!mounted) return;
      
      // Navigate to home
      Navigator.pushReplacement(
        context,
        MaterialPageRoute(builder: (_) => const MainMenuScreen()),
      );
    } catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(context)
          .showSnackBar(SnackBar(content: Text(AppLocalizations.of(context)!.loginError(e.toString()))));
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  Future<void> _promptBiometricEnrollment() async {
    if (!mounted) return;
    
    await showDialog(
      context: context,
      barrierDismissible: false,
      builder: (_) => AlertDialog(
        title: Text(AppLocalizations.of(context)!.enableBiometricLogin),
        content: Text(
          AppLocalizations.of(context)!.enableBiometricPrompt,
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: Text(AppLocalizations.of(context)!.notNow),
          ),
          ElevatedButton(
            onPressed: () async {
              Navigator.pop(context);
              // Small delay to allow dialog to close before biometric prompt
              await Future.delayed(const Duration(milliseconds: 200));
              await _enableBiometric();
            },
            child: Text(AppLocalizations.of(context)!.enable),
          ),
        ],
      ),
    );
  }

  Future<void> _enableBiometric() async {
    try {
      // Test biometric authentication
      final ok = await BiometricService().authenticate();
      if (ok) {
        final sp = await SharedPreferences.getInstance();
        await sp.setBool('biometric_enabled', true);
        if (!mounted) return;
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text(AppLocalizations.of(context)!.biometricEnabled)),
        );
      }
    } catch (e) {
      if (!mounted) return;
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text(AppLocalizations.of(context)!.failedEnableBiometric(e.toString()))),
      );
    }
  }

  Future<void> _loginWithBiometric() async {
    setState(() => _isLoading = true);
    try {
      final firmId = _firmCtrl.text.trim();

      // Must authenticate with device
      final ok = await BiometricService().authenticate();
      if (!ok) {
        if (!mounted) return;
        setState(() => _isLoading = false);
        return;
      }

      // Offline-with-biometric rule
      final can = await AuthService.canLoginOfflineWithBiometric(firmId: firmId);
      if (!can) {
        if (!mounted) return;
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(
          content: Text(AppLocalizations.of(context)!.biometricNotAllowed),
        ));
        return;
      }

      if (await AuthService.isExpired()) {
        if (!mounted) return;
        _showExpiryDialog(lock: true);
        return;
      } else if (await AuthService.shouldWarnExpiry()) {
        if (!mounted) return;
        _showExpiryDialog(lock: false);
      }

      if (!mounted) return;
      Navigator.pushReplacement(
        context,
        MaterialPageRoute(builder: (_) => const MainMenuScreen()),
      );
    } catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(context)
          .showSnackBar(SnackBar(content: Text(AppLocalizations.of(context)!.biometricFailed(e.toString()))));
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  void _showExpiryDialog({required bool lock}) async {
    final days = await AuthService.daysToExpiry();
    final msg = lock
        ? AppLocalizations.of(context)!.subscriptionExpired
        : AppLocalizations.of(context)!.subscriptionExpiresIn(days ?? 0);
    if (!mounted) return;
    showDialog(
      context: context,
      builder: (_) => AlertDialog(
        title: Text(AppLocalizations.of(context)!.subscription),
        content: Text(msg),
        actions: [
          TextButton(onPressed: () => Navigator.pop(context), child: Text(AppLocalizations.of(context)!.ok)),
        ],
      ),
    );
  }

  @override
  void dispose() {
    _firmCtrl.dispose();
    _mobileCtrl.dispose();
    _passCtrl.dispose();
    super.dispose();
  }

  Future<bool> _isBiometricEnabled() async {
    final sp = await SharedPreferences.getInstance();
    return sp.getBool('biometric_enabled') ?? false;
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    
    // Black background as requested (replacing Blue)
    const bgColor = Colors.black;
    const textColor = Colors.white;

    return Scaffold(
      backgroundColor: const Color(0xFF1E88E5), // Blue Background
      body: SafeArea(
        child: Center(
          child: ConstrainedBox(
            constraints: const BoxConstraints(maxWidth: 420),
            child: Padding(
              padding: const EdgeInsets.all(20),
              child: Form(
                key: _formKey,
                child: ListView(
                  shrinkWrap: true,
                  children: [
                    const SizedBox(height: 40),
                    // Logo or Title
                    Center(
                      child: Text(
                        'RuchiServ',
                        style: theme.textTheme.headlineMedium?.copyWith(
                          color: textColor,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                    ),
                    const SizedBox(height: 8),
                    Text(
                      AppLocalizations.of(context)!.signInContinue,
                      textAlign: TextAlign.center,
                      style: TextStyle(color: textColor.withOpacity(0.7)),
                    ),
                    const SizedBox(height: 28),

                    // Firm ID
                    TextFormField(
                      controller: _firmCtrl,
                      textInputAction: TextInputAction.next,
                      style: TextStyle(color: textColor),
                      decoration: InputDecoration(
                        labelText: AppLocalizations.of(context)!.firmId,
                        labelStyle: TextStyle(color: textColor.withOpacity(0.7)),
                        filled: true,
                        fillColor: Colors.white.withOpacity(0.1),
                        border: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(8),
                          borderSide: BorderSide.none,
                        ),
                        enabledBorder: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(8),
                          borderSide: BorderSide.none,
                        ),
                        focusedBorder: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(8),
                          borderSide: BorderSide(color: textColor, width: 1.5),
                        ),
                      ),
                      validator: (v) => (v == null || v.trim().isEmpty)
                          ? AppLocalizations.of(context)!.enterFirmId
                          : null,
                    ),
                    const SizedBox(height: 12),

                    // Mobile
                    TextFormField(
                      controller: _mobileCtrl,
                      keyboardType: TextInputType.phone,
                      textInputAction: TextInputAction.next,
                      style: TextStyle(color: textColor),
                      decoration: InputDecoration(
                        labelText: AppLocalizations.of(context)!.mobileNumber,
                        labelStyle: TextStyle(color: textColor.withOpacity(0.7)),
                        filled: true,
                        fillColor: Colors.white.withOpacity(0.1),
                        border: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(8),
                          borderSide: BorderSide.none,
                        ),
                        enabledBorder: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(8),
                          borderSide: BorderSide.none,
                        ),
                        focusedBorder: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(8),
                          borderSide: BorderSide(color: textColor, width: 1.5),
                        ),
                      ),
                      validator: (v) =>
                          (v == null || v.trim().isEmpty) ? AppLocalizations.of(context)!.enterMobile : null,
                    ),
                    const SizedBox(height: 12),

                    // Password
                    TextFormField(
                      controller: _passCtrl,
                      obscureText: true,
                      style: TextStyle(color: textColor),
                      decoration: InputDecoration(
                        labelText: AppLocalizations.of(context)!.password,
                        labelStyle: TextStyle(color: textColor.withOpacity(0.7)),
                        filled: true,
                        fillColor: Colors.white.withOpacity(0.1),
                        border: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(8),
                          borderSide: BorderSide.none,
                        ),
                        enabledBorder: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(8),
                          borderSide: BorderSide.none,
                        ),
                        focusedBorder: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(8),
                          borderSide: BorderSide(color: textColor, width: 1.5),
                        ),
                      ),
                      validator: (v) =>
                          (v == null || v.isEmpty) ? AppLocalizations.of(context)!.enterPassword : null,
                    ),
                    const SizedBox(height: 24),

                    _isLoading
                        ? const Center(child: CircularProgressIndicator(color: Colors.white))
                        : SizedBox(
                            width: double.infinity,
                            child: ElevatedButton(
                              onPressed: _login,
                              style: ElevatedButton.styleFrom(
                                backgroundColor: Colors.white,
                                foregroundColor: Colors.black, // Black text on white button
                                padding: const EdgeInsets.symmetric(vertical: 16),
                                shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(8),
                                ),
                              ),
                              child: Text(AppLocalizations.of(context)!.loginButton, style: const TextStyle(fontWeight: FontWeight.bold)),
                            ),
                          ),

                    const SizedBox(height: 16),

                    // Biometric Toggle Switch
                    if (_biometricAvailable)
                      FutureBuilder<bool>(
                        future: _isBiometricEnabled(),
                        builder: (context, snapshot) {
                          final enabled = snapshot.data ?? false;
                          return SwitchListTile(
                            title: Text(AppLocalizations.of(context)!.enableBiometricLogin, style: TextStyle(color: textColor)),
                            value: enabled,
                            activeColor: Colors.white,
                            activeTrackColor: Colors.green,
                            inactiveThumbColor: Colors.grey,
                            inactiveTrackColor: Colors.white.withOpacity(0.3),
                            onChanged: (val) async {
                              if (val) {
                                await _enableBiometric();
                              } else {
                                final sp = await SharedPreferences.getInstance();
                                await sp.setBool('biometric_enabled', false);
                                setState(() {});
                              }
                            },
                          );
                        },
                      ),

                    const SizedBox(height: 12),

                    Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        TextButton(
                          onPressed: () {
                            Navigator.push(
                              context,
                              MaterialPageRoute(builder: (_) => const RegisterChoiceScreen()),
                            );
                          },
                          child: Text(AppLocalizations.of(context)!.register, style: TextStyle(color: textColor)),
                        ),
                        TextButton(
                          onPressed: () {
                            Navigator.push(
                              context,
                              MaterialPageRoute(builder: (_) => const ForgotPasswordScreen()),
                            );
                          },
                          child: Text(AppLocalizations.of(context)!.forgotPassword, style: TextStyle(color: textColor)),
                        ),
                      ],
                    ),

                    const SizedBox(height: 24),
                  ],
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
